// DO NOT EDIT
// This file is generated by the java AllProfiles class
var _all_the_timer_profiles =  [
  {
    "matchers": [{
      "args": [
        1,
        2
      ],
      "pattern": " *([A-Z])=(\\d\\.\\d+)([^ ]?)",
      "event": "LANE_RESULT"
    }],
    "name": "\"The Champ\" (SmartLine/BestTrack)",
    "options": {
      "max_lanes": 6,
      "eol": "\r",
      "gate_state_is_knowable": true
    },
    "setup": {"commands": [
      "r",
      "or",
      "ol",
      "od",
      "op",
      "rs",
      "ol0",
      "op3"
    ]},
    "prober": {
      "responses": ["eTekGadget SmartLine Timer"],
      "pre_probe": {"commands": [""]},
      "probe": "v"
    },
    "setup_queries": [{
      "matchers": [{
        "args": [1],
        "pattern": "^(\\d)$",
        "event": "LANE_COUNT"
      }],
      "command": "on"
    }],
    "params": {
      "baud": 9600,
      "data": 8,
      "stop": 1,
      "parity": 0
    },
    "gate_watcher": {
      "matchers": [
        {
          "pattern": "^0$",
          "event": "GATE_CLOSED"
        },
        {
          "pattern": "^1$",
          "event": "GATE_OPEN"
        }
      ],
      "command": "rs"
    },
    "heat_prep": {
      "reset": "rg",
      "unmask": "om0",
      "lane": "1",
      "mask": "om"
    },
    "key": "TheChamp",
    "on": {
      "RACE_STARTED": {"commands": ["rg"]},
      "OVERDUE": {"commands": ["ra"]}
    }
  },
  {
    "matchers": [
      {
        "pattern": "S",
        "event": "RACE_STARTED"
      },
      {
        "args": [
          1,
          2
        ],
        "pattern": " *(\\d)=(\\d\\.\\d+)([^ ]?)",
        "event": "LANE_RESULT"
      }
    ],
    "name": "\"The Champ\" (SRM)",
    "options": {
      "max_lanes": 6,
      "eol": "\r",
      "gate_state_is_knowable": false
    },
    "prober": {
      "responses": ["SRM.*Enterprises"],
      "pre_probe": {"commands": [""]},
      "probe": "v"
    },
    "params": {
      "baud": 9600,
      "data": 8,
      "stop": 1,
      "parity": 0
    },
    "key": "TheChampSRM"
  },
  {
    "matchers": [{
      "args": [
        1,
        2
      ],
      "pattern": " *([A-Z])=(\\d+\\.\\d+)([^ ]?)",
      "event": "LANE_RESULT"
    }],
    "remote_start": {
      "has_remote_start": "fasttrack_has_automatic_gate_release",
      "command": "LG"
    },
    "name": "FastTrack K- or Q-series",
    "options": {
      "max_lanes": 6,
      "eol": "",
      "gate_state_is_knowable": true
    },
    "setup": {"commands": [
      "RE",
      "N1",
      "N2"
    ]},
    "prober": {
      "responses": [
        "Micro Wizard|MICRO WIZARD",
        "^K|Model: Q"
      ],
      "probe": "RV"
    },
    "setup_queries": [{
      "matchers": [{
        "pattern": "^[01][01]0[01] *[01][01][01]1$",
        "event": "FASTTRACK_NO_LASER_RESET"
      }],
      "command": "RF"
    }],
    "poll": {"MARK": {
      "condition": "fasttrack_poll_mark",
      "commands": {"commands": ["LR"]}
    }},
    "params": {
      "baud": 9600,
      "data": 8,
      "stop": 1,
      "parity": 0
    },
    "gate_watcher": {
      "matchers": [
        {
          "pattern": "^RG0|0$",
          "event": "GATE_OPEN"
        },
        {
          "pattern": "^RG1|1$",
          "event": "GATE_CLOSED"
        },
        {
          "pattern": "^X$",
          "event": "GATE_WATCHER_NOT_SUPPORTED"
        }
      ],
      "command": "RG"
    },
    "heat_prep": {
      "unmask": "MG",
      "lane": "A",
      "mask": "M"
    },
    "key": "FastTrack-K"
  },
  {
    "matchers": [{
      "args": [
        1,
        2
      ],
      "pattern": " *([A-Z])=(\\d\\.\\d+)([^ ]?)",
      "event": "LANE_RESULT"
    }],
    "name": "FastTrack P-series",
    "options": {
      "max_lanes": 6,
      "eol": "",
      "gate_state_is_knowable": false
    },
    "setup": {"commands": ["RF"]},
    "params": {
      "baud": 9600,
      "data": 8,
      "stop": 1,
      "parity": 0
    },
    "key": "FastTrack-P"
  },
  {
    "matchers": [
      {
        "args": [1],
        "pattern": "Number of Lanes:?\\s+(\\d)",
        "event": "LANE_COUNT"
      },
      {
        "pattern": "^G[oO]!?$",
        "event": "RACE_STARTED"
      },
      {
        "args": [
          1,
          2
        ],
        "pattern": "^Lane\\s+(\\d)\\s+0*(\\d+\\.\\d+)(\\s.*)?$",
        "event": "LANE_RESULT"
      },
      {
        "pattern": "Race Over.*",
        "event": "RACE_FINISHED"
      }
    ],
    "name": "The Judge (New Directions)",
    "options": {
      "max_lanes": 0,
      "eol": "\r",
      "gate_state_is_knowable": false
    },
    "setup": {"commands": []},
    "prober": {
      "responses": ["Checking Valid Lanes"],
      "probe": "*"
    },
    "params": {
      "baud": 9600,
      "data": 8,
      "stop": 1,
      "parity": 0
    },
    "gate_watcher": {
      "matchers": [],
      "command": "rs"
    },
    "heat_prep": {
      "unmask": "om0",
      "lane": "1",
      "mask": "om"
    },
    "key": "TheJudge",
    "on": {"OVERDUE": {"commands": ["*"]}}
  },
  {
    "matchers": [{
      "args": [
        1,
        2
      ],
      "pattern": "^\\s*(\\d)\\s+(\\d\\.\\d+)(\\s|)",
      "event": "LANE_RESULT"
    }],
    "name": "NewBold DT, TURBO, or DerbyStick",
    "options": {
      "max_lanes": 0,
      "eol": "",
      "gate_state_is_knowable": false
    },
    "setup": {"commands": [" "]},
    "params": {
      "baud": 1200,
      "data": 7,
      "stop": 2,
      "parity": 0
    },
    "heat_prep": {"reset": " "},
    "key": "NewBold"
  },
  {
    "matchers": [
      {
        "args": [1],
        "pattern": "^READY\\s*(\\d+)\\s+LANES",
        "event": "LANE_COUNT"
      },
      {
        "args": [
          1,
          2
        ],
        "pattern": "^\\s*(\\d)\\s+(\\d\\.\\d+)(\\s.*|)",
        "event": "LANE_RESULT"
      },
      {
        "pattern": "^RACE$",
        "event": "RACE_STARTED"
      }
    ],
    "name": "Derby Timer",
    "options": {
      "max_lanes": 0,
      "eol": "",
      "gate_state_is_knowable": true
    },
    "prober": {
      "responses": [
        "^RESET$",
        "^READY\\s*(\\d+)\\s+LANES"
      ],
      "probe": "R"
    },
    "params": {
      "baud": 9600,
      "data": 8,
      "stop": 1,
      "parity": 0
    },
    "gate_watcher": {
      "matchers": [
        {
          "pattern": "^U$",
          "event": "GATE_CLOSED"
        },
        {
          "pattern": "^D$",
          "event": "GATE_OPEN"
        }
      ],
      "command": "G"
    },
    "heat_prep": {
      "unmask": "C",
      "lane": "1",
      "mask": "M"
    },
    "key": "DerbyTimer.com",
    "on": {"OVERDUE": {"commands": ["F"]}}
  },
  {
    "matchers": [
      {
        "args": [1],
        "pattern": "numl=(\\d)",
        "event": "LANE_COUNT"
      },
      {
        "pattern": "^B$",
        "event": "RACE_STARTED"
      },
      {
        "args": [
          1,
          2
        ],
        "pattern": "(\\d) - (\\d+\\.\\d+)",
        "event": "LANE_RESULT"
      }
    ],
    "remote_start": {"command": "S"},
    "name": "PDT timer (https://www.dfgtec.com/pdt)",
    "options": {
      "max_lanes": 0,
      "eol": "",
      "gate_state_is_knowable": true
    },
    "setup": {"commands": [
      "R",
      "N"
    ]},
    "prober": {
      "responses": ["vert="],
      "pre_probe": {"commands": [""]},
      "probe": "V"
    },
    "params": {
      "baud": 9600,
      "data": 8,
      "stop": 1,
      "parity": 0
    },
    "gate_watcher": {
      "matchers": [
        {
          "pattern": "O",
          "event": "GATE_OPEN"
        },
        {
          "pattern": "\\.",
          "event": "GATE_CLOSED"
        }
      ],
      "command": "G"
    },
    "heat_prep": {
      "unmask": "U",
      "lane": "1",
      "mask": "M"
    },
    "key": "MiscJunk",
    "on": {"OVERDUE": {"commands": ["F"]}}
  },
  {
    "matchers": [
      {
        "pattern": "^B$",
        "event": "RACE_STARTED"
      },
      {
        "args": [
          1,
          2,
          3
        ],
        "pattern": "([1-8])=(\\d\\.\\d+)([!-/:-@])? *",
        "event": "LANE_RESULT"
      }
    ],
    "remote_start": {"command": "S"},
    "name": "Derby Magic timer",
    "options": {
      "max_lanes": 8,
      "eol": "",
      "gate_state_is_knowable": false
    },
    "setup": {"commands": ["R"]},
    "prober": {
      "responses": ["Derby Magic"],
      "probe": "V"
    },
    "params": {
      "baud": 19200,
      "data": 8,
      "stop": 1,
      "parity": 0
    },
    "key": "DerbyMagic"
  },
  {
    "matchers": [
      {
        "pattern": "^B$",
        "event": "RACE_STARTED"
      },
      {
        "args": [
          1,
          2,
          3
        ],
        "pattern": "([1-8])=(\\d\\.\\d+)([!-/:-@])? *",
        "event": "LANE_RESULT"
      }
    ],
    "remote_start": {"command": "S"},
    "name": "Derby Magic timer (9600)",
    "options": {
      "max_lanes": 8,
      "eol": "",
      "gate_state_is_knowable": false
    },
    "setup": {"commands": ["R"]},
    "prober": {
      "responses": ["Derby Magic"],
      "probe": "V"
    },
    "params": {
      "baud": 9600,
      "data": 8,
      "stop": 1,
      "parity": 0
    },
    "key": "DerbyMagic9600"
  },
  {
    "matchers": [
      {
        "pattern": "^B$",
        "event": "GATE_OPEN"
      },
      {
        "args": [
          1,
          2
        ],
        "pattern": "^\\s*(\\d)\\s+(\\d\\.\\d+)(\\s.*|)",
        "event": "LANE_RESULT"
      }
    ],
    "name": "Bert Drake timer",
    "options": {
      "max_lanes": 0,
      "eol": "",
      "gate_state_is_knowable": true
    },
    "prober": {
      "responses": ["Bert Drake"],
      "pre_probe": {"commands": ["R"]},
      "probe": "V"
    },
    "params": {
      "baud": 9600,
      "data": 8,
      "stop": 1,
      "parity": 0
    },
    "gate_watcher": {
      "matchers": [
        {
          "pattern": "^Gc$",
          "event": "GATE_CLOSED"
        },
        {
          "pattern": "^Go$",
          "event": "GATE_OPEN"
        }
      ],
      "command": "C"
    },
    "heat_prep": {"reset": "R"},
    "key": "BertDrake",
    "on": {"OVERDUE": {"commands": ["F"]}}
  },
  {
    "matchers": [{
      "args": [
        1,
        2
      ],
      "pattern": "^.*Place Single Lane Number:\\s*(\\d+)\\s+Time in Seconds:\\s*(\\d+\\.\\d{4,})",
      "event": "LANE_RESULT"
    }],
    "name": "JIT Racemaster",
    "options": {
      "max_lanes": 0,
      "eol": "",
      "gate_state_is_knowable": false
    },
    "setup": {"commands": ["L"]},
    "prober": {
      "responses": [
        "JIT, Inc.*Racemaster Software",
        "^Software Version"
      ],
      "probe": "V"
    },
    "params": {
      "baud": 9600,
      "data": 8,
      "stop": 1,
      "parity": 0
    },
    "heat_prep": {"reset": "R"},
    "key": "JIT"
  }
];

function all_profiles() {
  return _all_the_timer_profiles;
}
